### ISSUE TITLE
Zif.roll modifer default should be zero

### ISSUE THREAD

**Issue by davebytemfg** [DragonRuby/dragonruby-game-toolkit-contrib#80]
```
->  Zif.roll(dice: 1, sides: 1)
=> 3
```

That was unexpected until I looked up the def and then it made sense.

from zif.rb
```
  def self.roll(dice: 4, sides: 16, modifier: 2)
```

Might be better to default the modifier to zero.

Yes, I could also use the roll_raw call instead, but invoking the rule of least surprise.

**Comment by amirrajan** [comment]
wrong repo: https://github.com/danhealy/dragonruby-zif cc @danhealy

**Comment by davebytemfg** [comment]
My bad, moved to the right one, sooo many tabs....
