### ISSUE TITLE
Should this have been `static_sprites`?

### ISSUE THREAD

**Issue by mollerhoj** [DragonRuby/dragonruby-game-toolkit-contrib#81]
https://github.com/DragonRuby/dragonruby-game-toolkit-contrib/blob/8a29791f01d8b7d88bf9d53522e1fd9051564945/samples/09_performance/05_static_sprites_as_classes/app/main.rb#L42

**Comment by amirrajan** [comment]
yes this is a valid bug 👍

**Comment by owenbutler** [comment]
This is fixed in main/master now.  Suggest close the issue?
